### ISSUE TITLE
고유명사 통일 필요

### ISSUE THREAD

**Issue by inuit57** [marona42/ITBKoreanPatch#5]
![20210907002529_1](https://user-images.githubusercontent.com/24216471/132240354-6495a893-d248-4c1f-8f3d-fab095bf44f9.jpg)
![20210907000828_1](https://user-images.githubusercontent.com/24216471/132240362-93abeca3-94c2-44b0-9f1e-776607412fa7.jpg)

ACID 발사기 - 폐기처리 시설

아카이브 탱크 - 전차 

용어를 한쪽으로 통일하는 쪽이 좋아보입니다.

**Comment by marona42** [comment]
Archieve Tank의 경우 번역 원칙을 잡기 전 했던 번역이라 수정할 사항이 맞지만(탱크->전차),
ACID 발사기와 폐기처리 시설(disposal unit)은 원문 자체가 다릅니다. 여러 조종사 또한 같은 개체(A.C.I.D launcher)에 대해 각기 다른 표현을 하고 있습니다. 정황 상 혼란의 여지가 없으므로 수정 대상이 아닙니다.
